version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: tinyurl
      POSTGRES_PASSWORD: tinyurl
      POSTGRES_DB: tinyurl
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
networks:
  tinyurl:
    name: tinyurl
