version: "3.8"

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=keygen
    ports:
      - 5432:5432
networks:
  tinyurl_keygen:
    name: tinyurl_keygen
